<?php echo View::content() ?>

<h3 class="center"><b>RUTAS</b></h3>

<?php echo Html::linkAction('create', 'Nuevo registro +', "class='btn green right'")  ?>

<table class="centered table striped">

    <tr>
        <thead>
            <th>Id</th>
            <th>Nombre de Ruta</th>
            <th>Nombre de Parada</th>
            <th>municipio</th>
            <th>Activo</th>

        
        </thead>

        <?php foreach($listarutas->items as $item) : ?>

            <tr>
                <td><?php echo $item->id ?></td>
                <td><?php echo $item->nombre_ruta?></td>
                <td><?php echo $item->paradas ?></td>
                <td><?php echo $item->id_municipio?></td>
                <td>
                    <?php
                    if ($item->habilitado == 1) {
                        echo "Habilitado";
                    }
                    if ($item->habilitado == 0) {
                        echo "Inhabilitado";
                    }
                    ?>
                </td>
                <td>
                    <?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn"') ?>
                    <?php echo Html::linkAction("del/$item->id/", "Borrar", 'class="btn red"') ?>
                </td>
            </tr>

        <?php endforeach ?>
    </tr>
</table>