<div class="row section">

    <?php View::content(); ?>
    <h3 class="center"><b>Registro Cantones</b></h3>

    <?php echo Form::open(); ?>

    <div class="col s6">
        <label for="">Nombre del canton
            <?php echo Form::text('cantones.nombre_canton'); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="municipio">Municipio
            <?php
            $arreglo = array('Izalco'=>'Izalco', 'Sonzacate'=>'Sonzacate', 'Armenia'=>'Armenia', 'Nahuizalco'=>'Nahuizalco');
            echo Form::select('cantones.id_municipio', $arreglo);
            ?>
        </label>

        <br> <br>
    </div>

    <div class="col s6">
        <label for="habilitado">Habilitado
            <?php
            $arreglo = array('Inhabilitado', 'Habilitado');
            echo Form::select('cantones.habilitado', $arreglo);
            ?>
        </label>

        <br> <br>
    </div>

    <div class="col s12">
        <?php echo Form::submit('Guardar', 'class="btn green"') ?>
        <?php echo Form::reset('Limpiar', 'class="btn blue"') ?>
        <?php echo Html::linkAction('index', 'regresar', "class='btn red darken-1'") ?>
    </div>

    <?php echo Form::close(); ?>
</div>