<?php echo View::content() ?>

<h3 class="center"><b>Cantones</b></h3>

<?php echo Html::linkAction('create', 'Nuevo registro +', "class='btn green right'")  ?>

<table class="centered table striped">

    <tr>
        <thead>
            <th>Id</th>
            <th>Nombre del canton</th>
            <th>Activo</th>
            <th>Acciones</th>
        </thead>

        <?php foreach ($lista_cantones->items as $item) : ?>

    <tr>
        <td><?php echo $item->id ?></td>
        <td><?php echo $item->nombre_canton ?></td>
        <td>
            <?php
            if ($item->habilitado == 1) {
                echo "Habilitado";
            }
            if ($item->habilitado == 0) {
                echo "Inhabilitado";
            }
            ?>
        </td>
        <td>
            <?php echo Html::linkAction("edit/$item->id/", "Editar", 'class="btn blue"') ?>
            <?php echo Html::linkAction("del/$item->id/", "Borrar", 'class="btn red"') ?>
        </td>
    </tr>

<?php endforeach ?>
</tr>
</table>