<div class="row section">
    <?php View::content(); ?>
    <h3 class="center">Departamentos</h3>
    <?php echo Form::open(); ?>
        <div class="row">
            <div class="col s6">
                <label for="">nombre del Departamento
                    <?php echo Form::text('departamentos.nombre_departamento'); ?>
                </label>
            </div>

            <div class="col s6">
                <label for="habilitado">Habilitado
                    <?php 
                    $arreglo = array('Inhabilitado','Habilitado');
                    echo Form::select('departamentos.habilitado', $arreglo);
                    ?>
            
                </label>
            </div>
        </div>
        <div class="col s12">
            <?php echo Form::submit('Guardar',"class='btn teal'") ?>
            <?php echo Html::linkAction('index', 'regresar', "class='btn green'") ?>
        </div>
    <?= Form::close(); ?>
</div>