<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title><?php echo $titulo ?></title>
</head>


<body>

    <nav class="black">
        <div class="nav-wrapper">
            <a href="#" class="brand-logo"></a>
            <ul id="nav-mobile" class="lefth hide-on-med-and-down">
                <li><?php echo Html::Link('autobuses', 'Autobuses') ?></li>
                <li><?php echo Html::Link('cantones', 'Cantones') ?></li>
                <li><?php echo Html::Link('departamentos', 'Departamentos') ?></li>
                <li><?php echo Html::Link('municipios', 'Municipios') ?></li>
                <li><?php echo Html::Link('urbanizaciones', 'Urbanizaciones') ?></li>
                <li><?php echo Html::Link('zonas', 'Zonas') ?></li>
                <li><?php echo Html::Link('rutas', 'rutas') ?></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <?php View::content() ?>
    </div>



    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('.tabs').tabs();
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('select').formSelect();
        });
    </script>

    
</body>

</html>