<div class="row section">

    <?php View::content(); ?>
    <h3 class="center"><b>Registro Autobuses</b></h3>

    <?php echo Form::open(); ?>

        <div class="col s6">
            <label for="">Numero de la unidad
                <?php echo Form::text('autobuses.numero_unidad'); ?>
            </label>
        </div>

        <div class="col s6">
            <label for="">Numero de placa
                <?php echo Form::text('autobuses.numero_placa'); ?>
            </label>
        </div>

        <div class="col s12">
                <label for="habilitado">Habilitado
                    <?php
                        $arreglo = array('Inhabilitado','Habilitado');
                        echo Form::select('autobuses.habilitado',$arreglo);
                    ?>
                </label>
            </div>

        <div class="col s12">
            <?php echo Form::submit('Guardar', 'class="btn green"') ?>
            <?php echo Form::reset('Limpiar', 'class="btn blue"') ?>
            <?php echo Html::linkAction('index', 'regresar', "class='btn red darken-1'") ?>
        </div>

    <?php echo Form::close(); ?>
</div>