<div class="row section">

    <?php View::content(); ?>
    <h3 class="center"><b>Registro Autobuses</b></h3>

    <?php echo Form::open(); ?>

    <div class="col s6">
        <label for="">Numero de la unidad
            <?php echo Form::text('autobuses.numero_unidad'); ?>
        </label>
    </div>

    <div class="col s6">
        <label for="">Numero de placa
            <?php echo Form::text('autobuses.numero_placa'); ?>
        </label>

        <br> <br>
    </div>

    <div class="col s6">
        <label for="id_ruta">Ruta
            <?php
            $arreglo = array('53A' => '53A', '53A-1' => '53A-1', '53B' => '53B');
            echo Form::select('autobuses.id_ruta', $arreglo);
            ?>
        </label>
    </div>

    <div class="col s6">
        <label for="habilitado">Habilitado
            <?php
            $arreglo = array('Inhabilitado', 'Habilitado');
            echo Form::select('autobuses.habilitado', $arreglo);
            ?>
        </label>

        <br> <br>
    </div>

    <div class="col s12">
        <?= Form::hidden('autobuses.Id'); ?>
        <?php echo Form::submit('Guardar', 'class="btn green"') ?>
        <?php echo Form::reset('Limpiar', 'class="btn blue"') ?>
        <?php echo Html::linkAction('index', 'regresar', "class='btn red darken-1'") ?>
    </div>

    <?php echo Form::close(); ?>
</div>