<?php echo View::content() ?>

<h3 class="center"><b>Autobuses</b></h3>

<?php echo Html::linkAction('create', 'Nuevo registro +', "class='btn green right'")  ?>

<table class="centered table striped">

    <tr>
        <thead>
            <th>Id</th>
            <th>Numero de unidad</th>
            <th>Numero de placa</th>
            <th>Ruta</th>
            <th>Activo</th>
            <th>Acciones</th>
        </thead>

        <?php foreach ($lista_autobuses->items as $item) : ?>

    <tr>
        <td><?php echo $item->Id ?></td>
        <td><?php echo $item->numero_unidad ?></td>
        <td><?php echo $item->numero_placa ?></td>
        <td>
            <?php echo $item->id_ruta ?>
        </td>
        <td>
            <?php
            if ($item->habilitado == 1) {
                echo "Habilitado";
            }
            if ($item->habilitado == 0) {
                echo "Inhabilitado";
            }
            ?>
        </td>
        <td>
            <?php echo Html::linkAction("edit/$item->Id/", "Editar", 'class="btn blue"') ?>
            <?php echo Html::linkAction("del/$item->Id/", "Borrar", 'class="btn red"') ?>
        </td>
    </tr>

<?php endforeach ?>
</tr>
</table>