<div class="row">
    <?php echo View::content();?>
    <?php echo Form::open(); ?>
        <div class="col s6">
            <label>
                <?php echo Form::text('municipios.nombre_departamento');?>
            </label>
        </div>
        <div class="col s6">
            <label>
                <input type="checkbox"/>
                    <?php echo Form::check('municipios.habilitado','1','',true); ?>
                    <span>Habilitado</span>
            </label>
        </div>
        <div class="col s6">
            <label for="habilitado">
                <?php
                $arreglo = array('Inhabilitado', 'Habilitado');
                 echo Form::select('municipios.habilitado', $arreglo);
                ?>
            </label>
        </div>
        <div class="col s12">
            <?php echo Form::hidden('municipios.id');?>
            <?php echo Form::submit('guardar','class="btn green"') ?>
        </div>
    <?php echo Form::close(); ?>
</div>