<?php echo View::content(); ?>
    <h3 class="centered">Zonas</h3>

    <?php echo Html::linkAction('create','Nueva Zona', "class='btn green right'") ?>

<table class="centered table striped">
    <tr>
        <thead>
            <th>Id</th>
            <th>Nombre Zona</th>
            <th>Activo</th>
            <th>Acciones</th>
        </thead>
        <?php foreach ($Listazonas->items as $item): ?>
            <tr>
                <td><?php echo $item->id?></td>
                <td><?php echo $item->nombre_zona ?></td>
                <td>
                    <?php
                    if ($item->habilitado ==1){
                        echo "Habilitado";
                    };
                    if ($item->habilitado ==0){
                        echo "Inhabilitado";
                    }
                    ?>
                </td>
                <td>
                    <?php  echo Html::linkAction("edit/$item->id", "Editar", 'class="btn blue"') ?>
                    <?php  echo Html::linkAction("del/$item->id", "Borrar", 'class=" btn red"') ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tr>
</table>